version: '3.8'
services:
  product:
    build: ./product
    restart: always
    volumes:
      - '.app:/app'
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: always
    user: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - 'db-data:/var/lib/postgres'
  proxy:
    image: nginx:1.24.0
    restart: on-failure
    volumes:
      - ./conf.d:/etc/nginx/conf.data
    ports:
      - '9000:9000'
    depends_on:
      - product
volumes:
   db-data:      